version: "3"

services:

  celery:
    environment:
      - PRODUCTION=0
    volumes:
      - .:/app

  server:
    command: python manage.py runserver 0.0.0.0:8000 --migrate
    environment:
      - PRODUCTION=0
      - ALLOWED_HOSTS=*
    links:
      - db
      - redis
    volumes:
      - .:/app
