# Generated by Django 2.0.5 on 2018-09-17 04:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_day', models.PositiveSmallIntegerField(verbose_name='billing day')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBillEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, editable=False, verbose_name='date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_events', to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveSmallIntegerField(choices=[(1, 'Monthly'), (2, '6 months')])),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(editable=False, verbose_name='value')),
                ('date', models.DateField(auto_now=True, verbose_name='date')),
                ('user_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
